kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: agario
  namespace: agario
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'agario:master'
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:14-ubi8'
      dockerfilePath: Dockerfile
  source:
    type: Git
    git:
      uri: 'https://github.com/fjcloud/agar.io-clone.git'
